language: elixir
sudo: false
elixir:
  - 1.4
otp_release:
  - 19.3
  - 20.0-rc1
script: mix test.ci
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - steve@stevedomin.com
